name: manhunt
version: 0.1
authors: [ArcMissile, toomuchdog]
main: com.mypackage.Manhunt
api-version: 1.16
commands:
  manhuntinfo:
    description: tells how to use manhunt plugin
    usage: /<command>
  getcompass:
    description: gives the player thier first compass
    usage: /<command>
  titletest:
    description: title for testing
    usage: /<command> [player]
  disphunters:
    description: Displays the Users in the hunter collection (debug)
    usage: /<command>
  addhunter:
    description: Removes the Users in the hunter collection
    usage: /<command> [player]
  removehunter:
    description: Removes the Users in the hunter collection
    usage: /<command> [player]