name: manhunt
version: 0.1
authors: [ArcMissile, toomuchdog]
main: com.mypackage.Manhunt
api-version: 1.16
commands:
  manhuntinfo:
    description: tells how to use manhunt plugin
    usage: /manhuntinfo
  getcompass:
    description: gives the player thier first compass
    usage: /getcompass