name: manhunt
version: 0.1
authors: [ArcMissile, toomuchdog]
main: com.mypackage.Manhunt
api-version: 1.16.4
commands:
  manhuntinfo:
    description: tells how to use manhunt plugin
    usage: /manhuntinfo